version: "3.9"

services:
  springboot_api:
    container_name: springboot_api
    image: suareztorella-api:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://postgresql_db:5432/${ENV_DATABASE_NAME}
      - DATABASE_USERNAME=${ENV_DATABASE_USERNAME}
      - DATABASE_PASSWORD=${ENV_DATABASE_PASSWORD}
    depends_on:
      - postgresql_db
    networks:
      - suareztorella-network
  postgresql_db:
    container_name: postgresql_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${ENV_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${ENV_DATABASE_PASSWORD}
      POSTGRES_DB: ${ENV_DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - suareztorella-network
volumes:
  postgres_data:
networks:
  suareztorella-network:
    driver: bridge
